services:
    Mmalessa\Hermes\Receiver\HttpReceiver\HttpReceiverFactory:
        tags: ['hermes.receiver_factory']
    Mmalessa\Hermes\Receiver\KafkaReceiver\KafkaReceiverFactory:
        tags: ['hermes.receiver_factory']

    Mmalessa\Hermes\Console\:
        resource: '../../Console/*'
        tags: ['console.command']
        autoconfigure: true
        bind:
            $logger: '@monolog.logger.hermes'
#            $hermesConfiguration: '%hermes.configuration%'
#            $container: '@service_container' # FIXME - do it better
#            $receiver: '@hermes.receiver.my_http_receiver'
